package at.ac.tuwien.cloud.core;

public class DeclarativeResource {

	// @AutoGenerated
	private String id;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
